services:
  backend:
    build: ./backend
    container_name: flask_backend
    restart: always
    expose:
      - "8000"

  frontend:
    build: 
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=https://sea-catering.space
    container_name: next_frontend
    restart: always
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
