services:
  backend:
    build: ./backend
    container_name: flask_backend
    restart: always
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: next_frontend
    restart: always
    expose:
      - "3000"
    environment:
      - PYTHON_BACKEND_URL=http://backend:8000

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
